#pragma once
// Windows Header Files
#include <windows.h>

#include "game_functions.h"
#include "hook_wrapper.h"
// hooks
#include "binds.h"
#include "callbacks.h"
#include "camera_mods.h"
#include "character_select.h"
#include "chat.h"
#include "chatfilter.h"
#include "commands.h"
#include "directx.h"
#include "equip_item.h"
#include "find_pattern.h"
#include "floating_damage.h"
#include "game_str.h"
#include "helm_manager.h"
#include "io_ini.h"
#include "item_display.h"
#include "labels.h"
#include "looting.h"
#include "melody.h"
#include "music.h"
#include "named_pipe.h"
#include "nameplate.h"
#include "raid.h"
#include "survey.h"
#include "tellwindows.h"
#include "tick.h"
// other features
#include "alarm.h"
#include "assist.h"
#include "autofire.h"
#include "buff_timers.h"
#include "crash_handler.h"
#include "cycle_target.h"
#include "entity_manager.h"
#include "experience.h"
#include "netstat.h"
#include "npc_give.h"
#include "outputfile.h"
#include "patches.h"
#include "physics.h"
#include "player_movement.h"
#include "spellsets.h"
#include "target_ring.h"
#include "tooltip.h"
#include "ui_manager.h"
#include "zone_map.h"
#include "sky_uv_guard.h"

// #include "zeal_settings.h"
// #include "zeal.h"

extern HMODULE this_module;
